### ISSUE TITLE
Grade.py configuration not working

### ISSUE THREAD

**Issue by nickjm** [edx/xqueue-watcher#33]
https://github.com/edx/xqueue-watcher/blob/2a17af2bd66ee0f4ffae3147585118ac3cb868d7/conf.d/600.json#L11

Hi, I'm working on a course where we've created a custom `grade.py` file which we'd like to use. Unfortunately we tried adding the `gradepy` kwarg, however the xqwatcher service failed to start with the following error:

```
2018-05-29 17:59:26,213 - manager.py:128 -- enable_codejail [INFO]: configured codejail -> mit-686x /edx/app/xqwatcher/venvs/mit-686x/bin/python mit-686x
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/edx/app/xqwatcher/src/xqueue_watcher/__main__.py", line 4, in <module>
    sys.exit(main())
  File "xqueue_watcher/manager.py", line 187, in main
    manager.configure_from_directory(args.config_root)
  File "xqueue_watcher/manager.py", line 102, in configure_from_directory
    self.configure(json.load(queue_config))
  File "xqueue_watcher/manager.py", line 77, in configure
    watcher = self.client_from_config(queue_name, config)
  File "xqueue_watcher/manager.py", line 67, in client_from_config
    handler = handler(**kw)
  File "xqueue_watcher/jailedgrader.py", line 67, in __init__
    super(JailedGrader, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'gradepy'
```
Is there a new way to specify where the `grade.py` file is ?

**Comment by Yashwanth-2022** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tutor/xqueue-watcher/xqueue_watcher/__main__.py", line 4, in <module>
    sys.exit(main())
  File "/home/tutor/xqueue-watcher/xqueue_watcher/manager.py", line 183, in main
    manager.configure_from_directory(args.config_root)
  File "/home/tutor/xqueue-watcher/xqueue_watcher/manager.py", line 99, in configure_from_directory
    self.configure(json.load(queue_config))
  File "/home/tutor/xqueue-watcher/xqueue_watcher/manager.py", line 74, in configure
    watcher = self.client_from_config(queue_name, config)
  File "/home/tutor/xqueue-watcher/xqueue_watcher/manager.py", line 64, in client_from_config
    handler = handler(**kw)
TypeError: Grader.__init__() got an unexpected keyword argument 'gradepy'
I'm stuck with similar issue as yours. How did you resolve this issue ? Give me some insights on how to configure xqueue-watcher.
